---

- name: adding epel repo
  package: name={{item}} state=installed
  with_items:
    - epel-release

- name: adding mysql/mariadb packages
  package: name={{item}} state=installed
  with_items:
    - mariadb-server
    - MySQL-python 

- name: start mariadb
  service: name=mariadb state=started enabled=yes

- name: set the root password
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - "{{ansible_hostname}}"
    - localhost
    - 127.0.0.1
    - ::1
  ignore_errors: yes

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{inventory_hostname}}"
  ignore_errors: yes

- name: remove the test database
  mysql_db: name=test state=absent
  ignore_errors: yes

- name: set bind-address to default ipv4 in my.conf file
  lineinfile: dest=/etc/my.cnf line=bind-address={{ansible_default_ipv4.address}} state=present insertafter='^\[mysqld\]'
  notify: restart mysql

- name: configuring firewall services
  firewalld: service={{item}} permanent=true state=enabled
  with_items:
    - mysql

- name: reloading the firewall
  command: firewall-cmd --reload
